# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Incubator Blog 
tagline:          .gov Data Processing 
url:              http://ekgade.github.io
paginate:         1
baseurl:          /
author:
  name:           Emily Kalah Gade
  url:            
  email:          ekgade@uw.edu

